### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?      

### ISSUE THREAD

**Issue by FeralSmurf** [VinciGit00/Scrapegraph-ai#189]
In my venv, when I do:

pip install scrapegraphai

I always get this error in python 3.12.3: (it worked in python 3.11 tho)

      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

The system is up to date.

**Comment by PeriniM** [comment]
Hey @FeralSmurf I think there is a problem with the python 3.12 installation. The imp module is deprecated in python 3 versions, try running just `import imp` and see what it tells you [Stackoverflow](https://stackoverflow.com/questions/77401730/modulenotfounderror-no-module-named-imp)

btw I will try it in python 3.12 and get back to you

**Comment by VinciGit00** [comment]
Try with python 3.9
